apiVersion: aws.3sidedcube.com/v1alpha1
kind: App
metadata:
  name: example-app
spec:
  name: example-app
  region: eu-west-2
  environment: production
  accountID: 381491948780
  database:
    name: exampledb
    username: user
    engine: postgres
    class: db.t4g.micro
    version: "17.2"
    storage: 20
    multiAz: true