apiVersion: aws.3sidedcube.com/v1alpha1
kind: Network
metadata:
  name: example-app
spec:
  name: example-app
  region: eu-west-1
  cidrBlock: 10.0.0.0/16
  subnetCidrs:
    - 10.0.1.0/24
    - 10.0.2.0/24