name: Release

on:
  release:
    types:
      - published

jobs:
  deploy:
    name: Deploy to production
    runs-on: ubuntu-latest
    if: github.event.release.prerelease == false
    outputs:
      releases_created: ${{ steps.release.outputs.releases_created }}
    steps:
      - name: Run terraform apply
        run: echo "Applying terraform on 'production' ..."

      - name: Sync prerelease manifest
        env:
          RELEASE_TAG: ${{ github.event.release.tag_name }}
          MANIFEST_PATH: .github/prerelease-manifest.json
        run: |
          jq --arg tag "${RELEASE_TAG//v/}" '.["."] = $tag' $MANIFEST_PATH > temp.json \
            && mv temp.json $MANIFEST_PATH
