name: Release

on:
  push:
    branches:
      - main

concurrency:
  group: release

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    outputs:
      releases_created: ${{ steps.release.outputs.releases_created }}
      tag_name: ${{ steps.release.outputs.tag_name }}
    steps:
      - id: release
        name: Run release-please
        uses: googleapis/release-please-action@v4
        with:
          config-file: ".github/prerelease-config.json"
          manifest-file: ".github/prerelease-manifest.json"

  deploy-test:
    name: Deploy to Test
    runs-on: ubuntu-latest
    environment: test
    if: ${{ needs.release-please.outputs.releases_created == 'false' }}
    needs: release-please
    steps:
      - name: Configure
        run: |
          echo "${{ vars.EXAMPLE_VAR }}"
          echo "${{ secrets.EXAMPLE_SECRET }}"

      - name: Deploy
        run: echo "Deploying to test!"

  deploy-staging:
    name: Deploy to Staging
    runs-on: ubuntu-latest
    environment: staging
    if: ${{ needs.release-please.outputs.releases_created == 'true' && contains(needs.release-please.outputs.tag_name, 'beta') }}
    needs: release-please
    steps:
      - name: Configure
        run: |
          echo "${{ vars.EXAMPLE_VAR }}"
          echo "${{ secrets.EXAMPLE_SECRET }}"

      - name: Deploy
        run: echo "Deploying to staging!"

      - name: Run release-please
        uses: googleapis/release-please-action@v4
        with:
          config-file: ".github/release-config.json"
          manifest-file: ".github/release-manifest.json"

  deploy-production:
    name: Deploy to Production
    runs-on: ubuntu-latest
    environment: production
    if: ${{ needs.release-please.outputs.releases_created == 'true' && !contains(needs.release-please.outputs.tag_name, 'beta') }}
    needs: release-please
    steps:
      - name: Configure
        run: |
          echo "${{ vars.EXAMPLE_VAR }}"
          echo "${{ secrets.EXAMPLE_SECRET }}"

      - name: Deploy
        run: echo "Deploying to production!"

  publish:
    name: Publish images
    runs-on: ubuntu-latest
    environment: production
    needs: deploy-production
    strategy:
      matrix:
        arch: [amd64, arm64]
    steps:
      - name: Configure
        run: |
          echo "${{ vars.EXAMPLE_VAR }}"
          echo "${{ secrets.EXAMPLE_SECRET }}"

      - name: Build
        run: echo "Building for '${{ matrix.arch }}' ..."

      - name: Publish
        run: echo "Publishing for '${{ matrix.arch }}' ..."
